name: 'Delete feature branches'
inputs:  
  token:
    required: false
    default: ${{ github.token }}
  repos:  
    required: false
    default: ${{ github.repository }}
  prefix:
    required: false
    default: 'feature'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repos }}
    - ${{ inputs.prefix }}
