name: 'Delete feature branches'
inputs:
  token:
    required: true
  repos:
    required: true
  prefix:
    required: false
    default: 'feature'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repos }}
    - ${{ inputs.prefix }}
